CREATE TABLE my_BOOK
(
NAME nchar(100) Primary Key,  --unicode string data
DATE_PUBLISHING date NOT NULL CHECK (DATE_PUBLISHING>'2000.1.1' AND DATE_PUBLISHING<'2020.12.31'),
COUNT_PAGES int NOT NULL CHECK (COUNT_PAGES< 2000 AND COUNT_PAGES>1),
NAME_AUTHOR nchar(100) NOT NULL,
);



CREATE TABLE my_AUTHOR
(
NAME_AUTHOR nchar(100) PRIMARY KEY,
DATE_BIRTHDAY date CHECK (DATE_BIRTHDAY>'1000.1.1' AND DATE_BIRTHDAY<'2016.12.31'),

);
--Многие ко многим
CREATE TABLE my_AUTHORS_AND_BOOKS
(
NAME_BOOK nchar(100) NOT NULL,
NAME_AUTHOR nchar(100) NOT NULL,
CONSTRAINT role1 FOREIGN KEY (NAME_BOOK)
                      REFERENCES my_BOOK(NAME),
CONSTRAINT role2 FOREIGN KEY (NAME_AUTHOR)
                      REFERENCES my_AUTHOR(NAME_AUTHOR),
);

CREATE TABLE my_PAPPER_BOOK
(
CODE_COVER char(3000) NOT NULL CHECK (CODE_COVER IN ('S', 'H', 'Sp', 'Un')),                 
WEIGHT_KILO float NULL,
PRICE money NOT NULL CHECK (Price < 10000),
);

CREATE TABLE my_ELECTRO_BOOK
(
TYPE_FORMAT1 char(1000) CHECK (TYPE_FORMAT1  IN ('PDF', 'TXT', 'EPUB', 'MOBI','FB2')),
TYPE_FORMAT2 char(1000) CHECK (TYPE_FORMAT2  IN ('PDF', 'TXT', 'EPUB', 'MOBI','FB2')),
TYPE_FORMAT3 char(1000) CHECK (TYPE_FORMAT3  IN ('PDF', 'TXT', 'EPUB', 'MOBI','FB2')),
TYPE_FORMAT4 char(1000) CHECK (TYPE_FORMAT4  IN ('PDF', 'TXT', 'EPUB', 'MOBI','FB2')),
PRICE money NOT NULL CHECK (Price < 10000),
);
